name: Scheduled Workflow

on:
  schedule:
    - cron: '* * * * *' # Runs every minute

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"