## This workflow runs periodically.
##
## More details on https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule

name: Scheduled Workflow

on:
  schedule:
    - cron: '* * * * *' # Runs every minute

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"